### ISSUE TITLE
Documentation of GacUI Resource.xml attributes?

### ISSUE THREAD

**Issue by kapil-dhaimade** [vczh-libraries/Release#7]
Hi, Is there any simple documentation explaining attributes available in the UI Resource.xml in GacLib? Currently, the only option seems to be to follow the GacLib demo projects and learn it yourself.

**Comment by vczh** [comment]
I am writing the document, probably will spend the rest of the year. Basically you will see all useful types and properties in demo projects. There are a very small set of virtual types and virtual properties, like `<ComboBox/>`, which is actully a `<SelectableButton/>` with a predefined control template. I believe demo projects covers all of them.

The full list can be found [here](https://github.com/vczh-libraries/Release/blob/master/Import/GacUIReflection.cpp), I left XML comments as very short descriptions on classes and functions, these are things that you can access right away today.

**Comment by kapil-dhaimade** [comment]
Thank you @vczh 
I'll close this issue. However, I am evaluating GacLib for use in our team. I have multiple questions. Should I create multiple Issues for each question or just ask remaining questions in Comments to this issue?

**Comment by vczh** [comment]
@kapil-dhaimade you can just ask in this thread. By the way, I have not completed UI automation yet, just in case if you are interested in this area.

**Comment by kapil-dhaimade** [comment]
@vczh You got it. One question was about UI automation :) Thanks for answering that.
Few others:

- Is GacUI supported on Windows 7? Or is it from Win 8 and above?

- I think Animations are not supported?

- In some cases we'd like to show our UI embedded inside third-party applications, for example in a notification bar at top of a Word document, or as a floating widget in a Word document. Is such kind of UI possible with GacUI or it always works as a stand-alone dialog window?

**Comment by vczh** [comment]
@kapil-dhaimade 

- I did not test GacUI in Windows 7, but someone used it in Windows 7, so I believe it supports.
- Animation is [here](https://github.com/vczh-libraries/Release/tree/master/Tutorial/GacUI_Controls/Animation).
- I didn't expect GacUI to be embedded in another application. But you can call `vl::presentation::windows::GetWindowsForm(anyWindow->GetNativeWindow())->GetWindowHandle()` to get `HWND` from `GuiWindow`, and find any Windows API that helps your case.
- No
- `GacBuild.ps1` simply searches for all xml resources and run `GacGen.ps1` on all of them, with the incremental build feature enabled. I don't know what happened in your computer, but basically you need an extra [GacUI.xml](https://github.com/vczh-libraries/Release/blob/master/Tutorial/GacUI.xml). You need to pass the file path to `GacBuild.ps1`, so that it searches for xml resources that are placed inside the folder which contains `GacUI.xml`.

**Comment by kapil-dhaimade** [comment]
Thanks a lot for your help @vczh These answers really help.
I'll look into the Powershell script issue.
Also, closing the issue now

**Comment by vczh** [comment]
Hi, @kapil-dhaimade , I have authored document for the first library Vlpp, please take a look and see if that satisfies your need. Thsnk you.

http://vczh-libraries.github.io/doc/current/home.html

**Comment by vczh** [comment]
http://vczh-libraries.github.io/doc/current/home/registered.html

All reflectable types are now listed in the document page. For any item below, if (the result of replaceing `*` by a name `X`) appears in the list, then `<X>` is available in GacUI XMl Resource as a control, template or something else.

```C++
						L"presentation::controls::Gui*;"
						L"presentation::elements::Gui*Element;"
						L"presentation::compositions::Gui*Composition;"
						L"presentation::compositions::Gui*;"
						L"presentation::templates::Gui*;"
						L"system::*;"
						L"system::reflection::*;"
						L"presentation::*;"
						L"presentation::Gui*;"
						L"presentation::controls::*;"
						L"presentation::controls::list::*;"
						L"presentation::controls::tree::*;"
						L"presentation::elements::*;"
						L"presentation::elements::Gui*;"
						L"presentation::elements::text::*;"
						L"presentation::compositions::*;"
						L"presentation::templates::*;"
						L"presentation::theme::*";
```
